### ISSUE TITLE
Save Numbers

### ISSUE THREAD

**Issue by RushilP** [Guard13007/KSS#74]
I just uploaded a new file: [https://experiments.guard13007.com:8001/save/5](https://experiments.guard13007.com:8001/save/5)
however it should have been save 4 and the links to the page read: [https://experiments.guard13007.com:8001/save/4](https://experiments.guard13007.com:8001/save/4)
This throws errors, screenshots should be attached.
![Link to it (bottom left)](https://cloud.githubusercontent.com/assets/17555747/13549994/d0632720-e30a-11e5-927f-a94a39459461.png)
![The error](https://cloud.githubusercontent.com/assets/17555747/13549995/d06541b8-e30a-11e5-98c0-312108cbd9c6.png)
![The correct page](https://cloud.githubusercontent.com/assets/17555747/13549996/d06725c8-e30a-11e5-9ea7-67ffbc46a8dc.png)

**Comment by TangentFoxy** [comment]
I actually stumbled across this and fixed it already. I just haven't pushed that to the version of it publicly known about. I don't plan on pushing it there because I am running things on another server with a better domain. I haven't announced it yet, but when I do, I will redirect everyone to the new place.
 For now, if you change the URL to a 5, it still exists, it's just the URLs generated on the saves list were broken.

The only reason I haven't updated and moved everything yet is because I need to do some testing with a potential XSS vulnerability and I want to make sure the site is secure first.

**Comment by TangentFoxy** [comment]
Thank you so much for reporting it though!

**Comment by TangentFoxy** [comment]
Also, I just noticed, your error screenshot is actually of a _different_ bug, which has also since been fixed. xD Again, sorry it's not available yet, but I will be pushing a good update as soon as possible.

**Comment by RushilP** [comment]
OK, thanks
